### ISSUE TITLE
using with gene expression data

### ISSUE THREAD

**Issue by tyasird** [BIIG-UC3M/pMoSS#1]
Hi,

I wonder that can I use this approach with gene expression data.
I have ~15.000 genes with expressions for 200 samples.
I have tried to use with same parameters in example script, however it returns an error ```pMoSS/cross_validation.py:146, in read_pvalues(file_list)``` ```IndexError: index 0 is out of bounds for axis 1 with size 0``` because computed pvalues files empty there is no array in it. 

Is there anything I can do about it?
My input like this:

```
A1BG | A1BG-AS1 | A2M | A2ML1 | A3GALT2
0.348415 | 0.418065 | 0.458255 | 0.515604 | 0.450486
0.231103 | 0.389840 | 0.483299 | 0.408892 | 0.454666
0.234935 | 0.272578 | 0.465594 | 0.423093 | 0.347355
0.230452 | 0.286263 | 0.619479 | 0.457346 | 0.516015
0.396523 | 0.519556 | 0.323117 | 0.396117 | 0.421616
```
df.shape: `(200, 15633)
`

Thank you.

**Comment by esgomezm** [comment]
Hi @tyasird 

thank you for giving it a try! Do you want to compare the distributions between samples or between genes for the 200 samples? 

Could you please specify what are the steps you followed, how is your numpy array or maybe a screenshot of when is the error happening? This way I'll be able to know what's the problem.
