### ISSUE TITLE
pip-installable python package on pypi?

### ISSUE THREAD

**Issue by haesleinhuepf** [BIIG-UC3M/pMoSS#2]
Hi @esgomezm et al.,

this is a super cool repository! Congratulations to the paper that just came out!

I was wondering if you would be interested in publishing the code as pip-installable python package on pypi. It could then be reused in other projects and libraries. I presume this would very useful! However, it may also cost mid-/long-term maintenance efforts.

Let me know what your plans are in this context and/or if I can assist converting this repository into a python package on pypi.

Best,
Robert

**Comment by esgomezm** [comment]
Hey @haesleinhuepf 

Thank you for the suggestion! I should have done it back in time but I didn't know how to build it. 
Now you just got me into it! [Here](https://github.com/esgomezm/pMoSS/tree/pypi). It will take me some time to test that everything works well and not get too crazy about improving the code xD

Thanks!
Esti

**Comment by haesleinhuepf** [comment]
Awesome thanks for spending time on this! 🤩

**Comment by esgomezm** [comment]
Hey @haesleinhuepf 

The package is already available ;)
